CREATE USER cl WITH PASSWORD 'cl';

ALTER ROLE cl SUPERUSER;

CREATE DATABASE cl
  WITH OWNER = cl
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       CONNECTION LIMIT = -1;